### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by sherwin14** [MajidArabi/AndroidFilePicker#2]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.info, PID: 15280
    java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:77)
        at com.github.file_picker.extension.FileExtKt.getMusicCoverArt(FileExt.kt:55)
        at com.github.file_picker.adapter.ItemVH.bind(ItemVH.kt:50)
        at com.github.file_picker.adapter.ItemAdapter.onBindViewHolder(ItemAdapter.kt:30)
        at com.github.file_picker.adapter.ItemAdapter.onBindViewHolder(ItemAdapter.kt:12)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at androidx.appcompat.widget.LinearLayoutCompat.measureChildBeforeLayout(LinearLayoutCompat.java:1401)
        at androidx.appcompat.widget.LinearLayoutCompat.measureVertical(LinearLayoutCompat.java:685)
        at androidx.appcompat.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:575)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25161)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(BottomSheetBehavior.java:453)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25161)
E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1105)
        at android.view.View.measure(View.java:25161)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2294)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2691)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by MajidArabi** [comment]
hi @sherwin14 .
this error occurred with which version of library and in which version of Android?

**Comment by sherwin14** [comment]
@MajidArabi  I'm using the latest version which is v 0.0.9.

**Comment by MajidArabi** [comment]
> @MajidArabi I'm using the latest version which is v 0.0.9. and Android Version is Android 10.0


Done! You can update to 0.1.0 and this will be fixed :)

**Comment by sherwin14** [comment]
> > @MajidArabi I'm using the latest version which is v 0.0.9. and Android Version is Android 10.0
> 
> @sherwin14 Done! You can update to 0.1.0 and this will be fixed :)

Great! Tested now! It's working. Thank you so much @MajidArabi !
